name: 📚 Epic
description: Create an epic
labels: [epic]
body:
- type: markdown
  attributes:
    value: |
      An Epic is a significant feature or piece of work that doesn't
      easily fit into a single release. It will typically have a number of Stories
      and/or Tasks associated with it that can be delivered iteratively.
- type: textarea
  attributes:
    label: Description
    description: Describe the epic
- type: dropdown
  id: pricing
  attributes:
    label: Which customers would this be available to 
    description: Based on our [pricing principles](https://flowfuse.com/handbook/product/pricing/) features should be aligned between Cloud and CE/EE
    multiple: false
    options:
      - Everyone - CE/Starter/Team/Enterprise
      - Team + Enterprise Tiers (EE)
      - Enterprise Tier Only (EE)
      - Other (See comments)
- type: markdown
  attributes:
    value: |
      Hint: Please remember to provide an effort estimate, if possible, as outlined in our handbook.