name: Deploy feature branch to staging

on:
  pull_request:
    branches:
      - main

jobs:
  build_app:
    name: Build and contenerize application
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: 'forge-k8s'
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'registry.npmjs.org'
          scope: '@flowforge'
          always-auth: true

      - name: Build package
        run: |
          npm install --no-audit --no-fund && \
          npm install --no-audit --no-fund pg-hstore@^2.3.4 && \
          npm install --no-audit --no-fund @flowforge/kubernetes@^1.14.0 && \    
          npm run build

      - name: Debug
        run: |
          echo "current dir: $PWD"
          ls -la

      - name: Set variables
        run: | 
          echo "repository_owner_lower=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to temporary registry
        id: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build container image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "./docker/Dockerfile"
          tags: "ghcr.io/${{ env.repository_owner_lower }}/${{ env.IMAGE_NAME }}:${{ env.PR_NUMBER}}"
          push: true
          provenance: false
