name: Publish
on:
  workflow_dispatch:
    inputs:
      localfs_release_name:
        description: 'localfs package version'
        required: false
        default: 'nightly'
      localfs_ref:
        description: 'localfs package ref'
        required: false
  workflow_run:
    workflows: 
      - 'Backend Tests'
      - 'Backend Tests - postgres'
      - 'UI Tests'
    branches: 
      - main
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: |
      ( github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' ) ||
      ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' )
    uses: 'flowfuse/github-actions-workflows/.github/workflows/publish_node_package.yml@5e57b30ac6ed8478406b3b3f2780241d2f4dcd8f'
    with:
      package_name: flowforge
      build_package: true
      publish_package: true
      package_dependencies: |
        @flowforge/localfs
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}

  dispatch_container_build:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}

      - name: Trigger flowforge container build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: flowforge-container.yml
          repo: flowfuse/helm
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"flowforge_ref": "${{ github.ref }}", "flowforge_release_name": "${{ env.release_name }}"}'
