name: UI Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'
  pull_request:
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install
      # and run all Cypress tests
      - name: Run UI Unit Tests
        run: npm run test:unit:frontend
      - name: Run UI E2E (Cypress) Tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          config-file: config/cypress.config.js
          build: npm run build
          start: node test/e2e/frontend/test_environment.js
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-output
          path: |
            cypress/screenshots
            cypress/videos
