name: UI E2E (Cypress) Tests

on: [workflow_dispatch, push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          config-file: config/cypress.json
          build: npm run build
          start: node test/e2e/frontend/test_environment.js